# Site settings
title                    : "Fulong Li"
name                     : &name "Fulong Li"
description              : &description "Ph.D., IEEE Member, Researcher and Engineer in Power Electronics."
locale                   : "en-US"
url                      : "https://FulongLi.github.io"
baseurl                  : "" # Keep empty for user.github.io
repository               : "FulongLi/FulongLi.github.io"
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : false
timezone                 : Europe/London

# Author information
author:
  name             : "Dr. Fulong Li"
  avatar           : "Fulong.jfif"
  bio              : "Ph.D., IEEE Member, Researcher and Engineer in Power Electronics."
  location         : "Cardiff, UK"
  email            : "fulong.li@ieee.org"
  googlescholar    : "https://scholar.google.com/citations?user=Wn6STAIAAAAJ&hl=en"
  researchgate     : "https://www.researchgate.net/profile/Fulong-Li-2"
  github           : "https://github.com/FulongLi"
  linkedin         : "https://www.linkedin.com/in/fulong-li-6bb443127/"
  orcid            : "https://orcid.org/0000-0001-9972-7258"

# Social Sharing
social:
  type: Person
  name: "Dr. Fulong Li"
  links:
    - https://github.com/FulongLi
    - https://www.linkedin.com/in/fulong-li-6bb443127/
    - https://scholar.google.com/citations?user=Wn6STAIAAAAJ&hl=en

# Analytics (optional)
analytics:
  provider: "google-universal"
  google:
    tracking_id: "" # Add your Google Analytics ID if you have one

# Reading & Build
include:
  - .htaccess
  - _pages
  - files
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README
  - config
  - tmp
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .sass-cache
  - .jekyll-cache
  - .jekyll-assets-cache

encoding       : "utf-8"
markdown       : kramdown
highlighter    : rouge
markdown_ext   : "markdown,mkdown,mkdn,mkd,md"
excerpt_separator: "\n\n"

# Markdown Options
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Default settings for collections and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Collections (for custom sections like Research)
collections:
  pages:
    output: true
    permalink: /:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Archives (optional tag/category page rendering)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
