# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Fulong Li"
title_separator          : "-"
name                     : &name "Fulong Li"
description              : &description "Dr. Fulong Li — Researcher and Engineer in Power Electronics, DC Microgrids, and Wide-Bandgap Devices."
url                      : https://fulongli.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "FulongLi/FulongLi.github.io"
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               : false
atom_feed:
  path                   : # blank (default) uses feed.xml

# Social Sharing
twitter:
  username               : "li_fulong"


# Analytics
analytics:
  provider               : false


# Site Author
author:
  name             : "Dr. Fulong Li"
  avatar           : "avatar.jpg"
  bio              : "Ph.D., IEEE Member.<br>Researcher and Engineer in Power Electronics."
  location         : "Cardiff, UK"
  googlescholar    : "https://scholar.google.com/citations?user=Wn6STAIAAAAJ&hl=en"
  email            : "fulong.li@ieee.org"
  researchgate     : "https://www.researchgate.net/profile/Fulong-Li-2"
  github           : "FulongLi"
  linkedin         : "fulong-li-6bb443127"
  orcid            : "https://orcid.org/my-orcid?orcid=0000-0001-9972-7258"
  x                : "li_fulong"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .sass-cache
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - vendor
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  notes:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _notes
  - scope:
      path: ""
      type: notes
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# Outputting
permalink: /:categories/:title/
timezone: Europe/London


# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
